export const ADD_COMPETITOR = "ADD_COMPETITOR"

export const GET_DATA_PENDING = "GET_DATA_PENDING"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_ERROR = "GET_DATA_ERROR"

export const ADD_BOUTS = "ADD_BOUTS"
export const UPDATE_BOUT= "UPDATE_BOUT"

export const ADD_ERROR = "ADD_ERROR"